from django.contrib.auth import authenticate, login, logout
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView
from django.middleware.csrf import get_token as csrf_get_token

from .invitation_services import (
    AccountInvitationDomainError,
    RegistrationDomainError,
    accept_account_invitation,
    create_account_invitation,
    list_account_invitations,
    preview_account_invitation,
    register_account_from_invitation,
    revoke_account_invitation,
    serialize_account_invitation,
)
from .services import (
    list_user_sessions,
    register_user_session,
    revoke_all_sessions,
    revoke_other_sessions,
    revoke_user_session,
    serialize_user_session,
    unregister_session,
)


class CSRFEndpoint(APIView):
    """Public endpoint that ensures a CSRF cookie is set."""

    permission_classes = [AllowAny]

    def get(self, request):
        # get_token() ensures the CSRF cookie is set on the response.
        csrf_get_token(request)
        return Response({"detail": "CSRF cookie set"})


class LoginView(APIView):
    """Authenticate a user and create a server session.

    CSRF protection is enforced by csrf_protect in urls.py.
    """

    permission_classes = [AllowAny]

    def post(self, request):
        username = request.data.get("username", "")
        password = request.data.get("password", "")

        user = authenticate(username=username, password=password)
        if user is None:
            return Response(
                {"error": "Invalid username or password"},
                status=401,
            )

        login(request, user)

        # Register the POST-rotation session key. The session id was
        # regenerated by login(); the pre-authentication key must not be
        # the managed session identifier.
        register_user_session(user, request.session.session_key)

        return Response({
            "id": user.pk,
            "username": user.username,
            "firstName": user.first_name,
            "lastName": user.last_name,
            "email": user.email,
        })


class LogoutView(APIView):
    """Terminate the current Django session.

    CSRF protection is enforced by csrf_protect in urls.py.
    """

    permission_classes = [AllowAny]

    def post(self, request):
        session_key = request.session.session_key
        user = request.user
        logout(request)
        if session_key and user.is_authenticated:
            unregister_session(user, session_key)
        return Response({"detail": "Logged out"})


class MeView(APIView):
    """Return the current authenticated user.

    Unauthenticated requests receive a 401.
    """

    permission_classes = [IsAuthenticated]

    def get(self, request):
        user = request.user
        return Response({
            "id": user.pk,
            "username": user.username,
            "firstName": user.first_name,
            "lastName": user.last_name,
            "email": user.email,
        })


class SessionListView(APIView):
    """List the current user's active sessions.

    Only non-secret metadata is returned; the raw Django session key is
    never exposed. Expired/revoked sessions are not listed.
    """

    permission_classes = [IsAuthenticated]

    def get(self, request):
        current_session_key = request.session.session_key
        rows = list_user_sessions(request.user, current_session_key)
        return Response({
            "sessions": [
                serialize_user_session(row, current_session_key)
                for row in rows
            ],
        })


class SessionRevokeView(APIView):
    """Revoke one session of the current user by its public id.

    Unknown ids and ids owned by another user both answer the same
    non-leaking 404. Revoking an already-revoked session is a 404.
    """

    permission_classes = [IsAuthenticated]

    def post(self, request, session_id):
        revoked = revoke_user_session(request.user, session_id)
        if not revoked:
            return Response(
                {"error": "Session not found"},
                status=404,
            )
        return Response({"detail": "Session revoked"})


class SessionRevokeOthersView(APIView):
    """Revoke every session of the current user except this one."""

    permission_classes = [IsAuthenticated]

    def post(self, request):
        revoke_other_sessions(request.user, request.session.session_key)
        return Response({"detail": "Other sessions revoked"})


class SessionRevokeAllView(APIView):
    """Revoke every session of the current user, including this one."""

    permission_classes = [IsAuthenticated]

    def post(self, request):
        revoke_all_sessions(request.user)
        return Response({"detail": "All sessions revoked"})


class AccountInvitationListCreateView(APIView):
    """List (GET) or create (POST) the current user's account invitations.

    Creation requires an authenticated active account, returns the raw
    token exactly once (201), and atomically replaces any existing
    effective pending invitation for the same normalized email. Listing
    returns only the current user's invitations with their effective
    lifecycle state — never the raw token or its digest.
    """

    permission_classes = [IsAuthenticated]

    def get(self, request):
        rows = list_account_invitations(request.user)
        return Response({
            "invitations": [
                serialize_account_invitation(row) for row in rows
            ],
        })

    def post(self, request):
        invited_email = request.data.get("targetEmail") or ""
        try:
            invitation, raw_token = create_account_invitation(
                actor=request.user, invited_email=invited_email
            )
        except AccountInvitationDomainError as exc:
            return Response({"error": exc.message}, status=400)
        data = serialize_account_invitation(invitation)
        data["token"] = raw_token
        return Response(data, status=201)


class AccountInvitationRevokeView(APIView):
    """Revoke one of the current user's still-pending invitations.

    Unknown ids and ids of other inviters answer the same non-leaking
    404. An invitation that is no longer effectively pending cannot be
    revoked and also answers 404 (no state is revealed).
    """

    permission_classes = [IsAuthenticated]

    def post(self, request, public_id):
        try:
            invitation = revoke_account_invitation(
                actor=request.user, public_id=public_id
            )
        except AccountInvitationDomainError as exc:
            return Response({"error": exc.message}, status=400)
        if invitation is None:
            return Response(
                {"error": "Invitation not found"},
                status=404,
            )
        return Response({"detail": "Invitation revoked"})


class AccountInvitationAcceptView(APIView):
    """Accept an account invitation with its raw token.

    Existing-account flow: binds the invitation to the authenticated
    current user (normalized email must match the invited email). No new
    account and no ResearchGroup/Project membership is created. The future
    registration flow calls the same domain service.
    """

    permission_classes = [IsAuthenticated]

    _STATUS_BY_CODE = {
        "not_found": 404,
        "expired": 410,
        "email_mismatch": 400,
    }

    def post(self, request):
        try:
            invitation = accept_account_invitation(
                actor=request.user, token=request.data.get("token")
            )
        except AccountInvitationDomainError as exc:
            return Response(
                {"error": exc.message},
                status=self._STATUS_BY_CODE.get(exc.code, 400),
            )
        data = serialize_account_invitation(invitation)
        data["acceptedUserId"] = invitation.accepted_by_id
        return Response(data)


class RegisterView(APIView):
    """Invite-only self-service registration.

    Unauthenticated browser mutation; CSRF is enforced by csrf_protect in
    urls.py (the same pattern as login). The client supplies only the
    user-created fields required by the current User model (username and
    password); the invited email is authoritative and comes exclusively from
    the invitation. A client-supplied authoritative ``email`` is rejected
    fail-closed rather than silently trusted or ignored.

    On success the new account is authenticated through the normal revocable
    Django session architecture and the post-rotation session key is
    registered in the UserSession registry — exactly like login. No
    ResearchGroup or Project membership is created and no access is granted.
    """

    permission_classes = [AllowAny]

    _STATUS_BY_CODE = {
        "invalid_token": 404,
        "already_used": 410,
        "revoked": 410,
        "expired": 410,
        "account_exists": 409,
        "username": 400,
        "password": 400,
    }

    def post(self, request):
        # Fail-closed: the invited email must never be client-supplied.
        if "email" in request.data:
            return Response(
                {"error": "The e-mail address cannot be provided."},
                status=400,
            )
        try:
            user = register_account_from_invitation(
                token=request.data.get("token"),
                username=request.data.get("username"),
                password=request.data.get("password"),
            )
        except RegistrationDomainError as exc:
            return Response(
                {"error": exc.message, "code": exc.code},
                status=self._STATUS_BY_CODE.get(exc.code, 400),
            )

        # Authenticate with the normal revocable Django session
        # architecture and register the post-rotation session key — the same
        # path as login. login() rotates the session id (no fixation).
        login(request, user)
        register_user_session(user, request.session.session_key)

        return Response(
            {
                "id": user.pk,
                "username": user.username,
                "firstName": user.first_name,
                "lastName": user.last_name,
                "email": user.email,
            },
            status=201,
        )


class RegistrationInvitationPreviewView(APIView):
    """Non-consuming preview of a registration invitation token.

    Lets a person without an account confirm a token is valid and see the
    invited email, its expiry, and whether an account already exists, before
    registering. It does not authenticate, does not create or accept
    anything, and does not consume the invitation. CSRF is enforced by
    csrf_protect in urls.py (unauthenticated browser POST).
    """

    permission_classes = [AllowAny]

    def post(self, request):
        try:
            data = preview_account_invitation(request.data.get("token"))
        except RegistrationDomainError as exc:
            return Response(
                {"error": exc.message},
                status=404 if exc.code == "invalid_token" else 400,
            )
        return Response(data)
