from django.contrib.auth import authenticate, login, logout
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView
from django.middleware.csrf import get_token as csrf_get_token

from .services import (
    list_user_sessions,
    register_user_session,
    revoke_all_sessions,
    revoke_other_sessions,
    revoke_user_session,
    serialize_user_session,
    unregister_session,
)


class CSRFEndpoint(APIView):
    """Public endpoint that ensures a CSRF cookie is set."""

    permission_classes = [AllowAny]

    def get(self, request):
        # get_token() ensures the CSRF cookie is set on the response.
        csrf_get_token(request)
        return Response({"detail": "CSRF cookie set"})


class LoginView(APIView):
    """Authenticate a user and create a server session.

    CSRF protection is enforced by csrf_protect in urls.py.
    """

    permission_classes = [AllowAny]

    def post(self, request):
        username = request.data.get("username", "")
        password = request.data.get("password", "")

        user = authenticate(username=username, password=password)
        if user is None:
            return Response(
                {"error": "Invalid username or password"},
                status=401,
            )

        login(request, user)

        # Register the POST-rotation session key. The session id was
        # regenerated by login(); the pre-authentication key must not be
        # the managed session identifier.
        register_user_session(user, request.session.session_key)

        return Response({
            "id": user.pk,
            "username": user.username,
            "firstName": user.first_name,
            "lastName": user.last_name,
            "email": user.email,
        })


class LogoutView(APIView):
    """Terminate the current Django session.

    CSRF protection is enforced by csrf_protect in urls.py.
    """

    permission_classes = [AllowAny]

    def post(self, request):
        session_key = request.session.session_key
        user = request.user
        logout(request)
        if session_key and user.is_authenticated:
            unregister_session(user, session_key)
        return Response({"detail": "Logged out"})


class MeView(APIView):
    """Return the current authenticated user.

    Unauthenticated requests receive a 401.
    """

    permission_classes = [IsAuthenticated]

    def get(self, request):
        user = request.user
        return Response({
            "id": user.pk,
            "username": user.username,
            "firstName": user.first_name,
            "lastName": user.last_name,
            "email": user.email,
        })


class SessionListView(APIView):
    """List the current user's active sessions.

    Only non-secret metadata is returned; the raw Django session key is
    never exposed. Expired/revoked sessions are not listed.
    """

    permission_classes = [IsAuthenticated]

    def get(self, request):
        current_session_key = request.session.session_key
        rows = list_user_sessions(request.user, current_session_key)
        return Response({
            "sessions": [
                serialize_user_session(row, current_session_key)
                for row in rows
            ],
        })


class SessionRevokeView(APIView):
    """Revoke one session of the current user by its public id.

    Unknown ids and ids owned by another user both answer the same
    non-leaking 404. Revoking an already-revoked session is a 404.
    """

    permission_classes = [IsAuthenticated]

    def post(self, request, session_id):
        revoked = revoke_user_session(request.user, session_id)
        if not revoked:
            return Response(
                {"error": "Session not found"},
                status=404,
            )
        return Response({"detail": "Session revoked"})


class SessionRevokeOthersView(APIView):
    """Revoke every session of the current user except this one."""

    permission_classes = [IsAuthenticated]

    def post(self, request):
        revoke_other_sessions(request.user, request.session.session_key)
        return Response({"detail": "Other sessions revoked"})


class SessionRevokeAllView(APIView):
    """Revoke every session of the current user, including this one."""

    permission_classes = [IsAuthenticated]

    def post(self, request):
        revoke_all_sessions(request.user)
        return Response({"detail": "All sessions revoked"})
