# Generated by Django 5.2.17 on 2026-08-13 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_research_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'research group',
                'verbose_name_plural': 'research groups',
                'db_table': 'research_groups_research_group',
            },
        ),
        migrations.CreateModel(
            name='ResearchGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], max_length=16)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('research_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='research_groups.researchgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'research_groups_membership',
                'constraints': [models.UniqueConstraint(fields=('research_group', 'user'), name='research_groups_researchgroupmembership_unique_group_user')],
                'unique_together': {('research_group', 'user')},
            },
        ),
    ]
