# Generated by Django 5.2.17 on 2026-10-03 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceNavigationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_group_order', models.JSONField(default=list)),
                ('expanded_research_groups', models.JSONField(default=list)),
                ('expanded_project_sections', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_navigation_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'workspace navigation preferences',
                'verbose_name_plural': 'workspace navigation preferences',
                'db_table': 'research_groups_workspace_navigation_preferences',
            },
        ),
    ]
