# Generated by Django 5.2.17 on 2026-08-18 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_harden_ownership'),
        ('research_groups', '0001_initial'),
        ('work_items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=80)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='audit_events_as_actor', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='projects.project')),
                ('research_group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='audit_events', to='research_groups.researchgroup')),
                ('subject_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='audit_events_as_subject', to=settings.AUTH_USER_MODEL)),
                ('work_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='work_items.workitem')),
            ],
            options={
                'db_table': 'audit_history_event',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['research_group', '-created_at'], name='audit_rg_created_idx'), models.Index(fields=['event_type'], name='audit_event_type_idx')],
            },
        ),
    ]
