# Generated by Django 5.2.17 on 2026-09-14 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_history', '0001_initial'),
        ('meetings', '0013_remove_meetingitemfollowup_meetings_follow_up_target_item_is_new_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='meetings.meeting'),
        ),
    ]
