# Generated by Django 5.2.17 on 2026-08-17 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research_groups', '0001_initial'),
        ('work_items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('completed', 'Completed')], default='upcoming', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_meetings', to=settings.AUTH_USER_MODEL)),
                ('research_group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='meetings', to='research_groups.researchgroup')),
            ],
            options={
                'db_table': 'meetings_meeting',
                'ordering': ['scheduled_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MeetingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('position', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('discussed', 'Discussed')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_meeting_items', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='meetings.meeting')),
            ],
            options={
                'db_table': 'meetings_item',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MeetingItemWorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_meeting_work_item_links', to=settings.AUTH_USER_MODEL)),
                ('meeting_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_item_relations', to='meetings.meetingitem')),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_item_relations', to='work_items.workitem')),
            ],
            options={
                'db_table': 'meetings_item_work_item',
            },
        ),
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_relations', to='meetings.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='meeting_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meetings_participant',
            },
        ),
        migrations.AddConstraint(
            model_name='meetingitem',
            constraint=models.UniqueConstraint(fields=('meeting', 'position'), name='meetings_item_unique_meeting_position'),
        ),
        migrations.AddConstraint(
            model_name='meetingitemworkitem',
            constraint=models.UniqueConstraint(fields=('meeting_item', 'work_item'), name='meetings_item_work_item_unique_pair'),
        ),
        migrations.AddConstraint(
            model_name='meetingparticipant',
            constraint=models.UniqueConstraint(fields=('meeting', 'user'), name='meetings_participant_unique_meeting_user'),
        ),
    ]
