# Generated by Django 5.2.17 on 2026-08-30 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
        ('research_groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_meeting_series', to=settings.AUTH_USER_MODEL)),
                ('research_group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='meeting_series', to='research_groups.researchgroup')),
            ],
            options={
                'db_table': 'meetings_series',
                'ordering': ['title', 'id'],
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='meetings.meetingseries'),
        ),
        migrations.CreateModel(
            name='MeetingSeriesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('position', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('meeting_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_sections', to='meetings.meetingseries')),
            ],
            options={
                'db_table': 'meetings_series_section',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MeetingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('position', models.PositiveIntegerField()),
                ('is_visible', models.BooleanField(default=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_sections', to='meetings.meeting')),
                ('source_series_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='meetings.meetingseriessection')),
            ],
            options={
                'db_table': 'meetings_section',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='meetingseriessection',
            constraint=models.UniqueConstraint(fields=('meeting_series', 'position'), name='meetings_series_section_unique_series_position'),
        ),
        migrations.AddConstraint(
            model_name='meetingsection',
            constraint=models.UniqueConstraint(fields=('meeting', 'position'), name='meetings_section_unique_meeting_position'),
        ),
    ]
