# Generated by Django 5.2.17 on 2026-08-31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0002_add_meeting_series_and_sections"),
        ("projects", "0004_workitemlabeldefinition_workitemstatusdefinition_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="meetings",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="scope",
            field=models.CharField(
                choices=[
                    ("group", "Research group"),
                    ("project", "Project"),
                ],
                default="group",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="meetingseries",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="meeting_series",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="meetingseries",
            name="scope",
            field=models.CharField(
                choices=[
                    ("group", "Research group"),
                    ("project", "Project"),
                ],
                default="group",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="meeting",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("project__isnull", True), ("scope", "group"))
                    | models.Q(("project__isnull", False), ("scope", "project"))
                ),
                name="meetings_meeting_scope_project_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="meetingseries",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("project__isnull", True), ("scope", "group"))
                    | models.Q(("project__isnull", False), ("scope", "project"))
                ),
                name="meetings_series_scope_project_consistent",
            ),
        ),
    ]
