# Generated by Django 5.2.17 on 2026-09-03 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_meetingitem_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='authored_meeting_notes', to=settings.AUTH_USER_MODEL)),
                ('meeting_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_relations', to='meetings.meetingitem')),
            ],
            options={
                'db_table': 'meetings_note',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
