# Generated by Django 5.2.17 on 2026-09-04 14:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0008_meetingitemworkitem_meeting_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingitem',
            name='status',
            field=models.CharField(choices=[('not_discussed', 'Not discussed'), ('discussing', 'Discussing'), ('done', 'Done'), ('follow_up', 'Follow-up')], default='not_discussed', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='meetingitem',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'discussing')), fields=('meeting',), name='meetings_item_single_discussing_per_meeting'),
        ),
    ]
