# Generated by Django 5.2.17 on 2026-09-09 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0011_current_item_and_outcome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingItemFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('needs_reschedule', 'Needs reschedule'), ('cancelled', 'Cancelled')], default='scheduled', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_meeting_item_follow_ups', to=settings.AUTH_USER_MODEL)),
                ('source_meeting_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_schedules', to='meetings.meetingitem')),
                ('target_meeting', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='targeted_follow_up_schedules', to='meetings.meeting')),
                ('target_meeting_item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='source_follow_up_schedules', to='meetings.meetingitem')),
                ('target_meeting_section', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='targeted_follow_up_schedules', to='meetings.meetingsection')),
            ],
            options={
                'db_table': 'meetings_item_follow_up',
                'ordering': ['created_at', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('target_meeting_item', models.F('source_meeting_item')), _negated=True), name='meetings_follow_up_target_item_is_new'), models.UniqueConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), fields=('source_meeting_item',), name='meetings_follow_up_one_active_per_source')],
            },
        ),
    ]
