# Generated by Django 5.2.17 on 2026-09-10 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0012_meetingitemfollowup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='meetingitemfollowup',
            name='meetings_follow_up_target_item_is_new',
        ),
        migrations.AddField(
            model_name='meetingitemfollowup',
            name='target_item_created_position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetingitemfollowup',
            name='target_pristine',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meetingitemfollowup',
            name='target_meeting_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_follow_up_schedules', to='meetings.meetingitem'),
        ),
        migrations.AddConstraint(
            model_name='meetingitemfollowup',
            constraint=models.CheckConstraint(condition=models.Q(('target_meeting_item__isnull', True), models.Q(('target_meeting_item', models.F('source_meeting_item')), _negated=True), _connector='OR'), name='meetings_follow_up_target_item_is_new'),
        ),
        migrations.AddConstraint(
            model_name='meetingitemfollowup',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'cancelled'), ('target_meeting_item__isnull', False), _connector='OR'), name='meetings_follow_up_active_target_required'),
        ),
    ]
