# Generated by Django 5.2.17 on 2026-09-22 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0013_remove_meetingitemfollowup_meetings_follow_up_target_item_is_new_and_more'),
        ('projects', '0006_workitemtypedefinition_kind'),
        ('research_groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRecurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('group', 'Research group'), ('project', 'Project')], default='group', max_length=16)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=16)),
                ('interval', models.PositiveSmallIntegerField()),
                ('weekdays', models.JSONField(default=list)),
                ('start_date', models.DateField()),
                ('local_time', models.TimeField()),
                ('timezone_name', models.CharField(max_length=64)),
                ('end_mode', models.CharField(choices=[('no_end', 'No end'), ('end_date', 'End date'), ('count', 'Count')], default='no_end', max_length=16)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('occurrence_count', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_meeting_recurrences', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='meeting_recurrences', to='projects.project')),
                ('research_group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='meeting_recurrences', to='research_groups.researchgroup')),
            ],
            options={
                'db_table': 'meetings_recurrence',
                'ordering': ['start_date', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('project__isnull', True), ('scope', 'group')), models.Q(('project__isnull', False), ('scope', 'project')), _connector='OR'), name='meetings_recurrence_scope_project_consistent'), models.CheckConstraint(condition=models.Q(('interval__gte', 1)), name='meetings_recurrence_interval_positive'), models.CheckConstraint(condition=models.Q(models.Q(('end_date__isnull', True), ('end_mode', 'no_end'), ('occurrence_count__isnull', True)), models.Q(('end_date__isnull', False), ('end_mode', 'end_date'), ('occurrence_count__isnull', True)), models.Q(('end_date__isnull', True), ('end_mode', 'count'), ('occurrence_count__isnull', False)), _connector='OR'), name='meetings_recurrence_end_mode_consistent'), models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='meetings_recurrence_end_date_not_before_start'), models.CheckConstraint(condition=models.Q(('frequency', 'weekly'), ('weekdays', []), _connector='OR'), name='meetings_recurrence_weekdays_only_weekly')],
            },
        ),
    ]
