# Generated by Django 5.2.17 on 2026-09-22 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0014_meetingrecurrence'),
        ('projects', '0006_workitemtypedefinition_kind'),
        ('research_groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='original_scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='recurrence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='materialized_meetings', to='meetings.meetingrecurrence'),
        ),
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('original_scheduled_at__isnull', True), ('recurrence__isnull', True)), models.Q(('original_scheduled_at__isnull', False), ('recurrence__isnull', False)), _connector='OR'), name='meetings_meeting_recurrence_original_paired'),
        ),
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.UniqueConstraint(fields=('recurrence', 'original_scheduled_at'), name='meetings_meeting_unique_recurrence_occurrence'),
        ),
    ]
