# Generated by Django 5.2.17 on 2026-09-22 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0015_meeting_recurrence_materialization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRecurrenceExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_scheduled_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_meeting_recurrence_exclusions', to=settings.AUTH_USER_MODEL)),
                ('recurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to='meetings.meetingrecurrence')),
            ],
            options={
                'db_table': 'meetings_recurrence_exclusion',
                'ordering': ['original_scheduled_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('recurrence', 'original_scheduled_at'), name='meetings_recurrence_exclusion_unique_occurrence')],
            },
        ),
    ]
