# Generated by Django 5.2.17 on 2026-08-14 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_harden_ownership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('epic', 'Epic'), ('milestone', 'Milestone'), ('deliverable', 'Deliverable'), ('task', 'Task')], max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('review', 'Review'), ('done', 'Done')], default='todo', max_length=16)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('blocked_reason', models.TextField(blank=True, default='')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_work_items', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='work_items.workitem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_items', to='projects.project')),
            ],
            options={
                'verbose_name': 'work item',
                'verbose_name_plural': 'work items',
                'db_table': 'work_items_work_item',
            },
        ),
        migrations.CreateModel(
            name='WorkItemAssignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='work_item_assignments', to=settings.AUTH_USER_MODEL)),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignee_relations', to='work_items.workitem')),
            ],
            options={
                'verbose_name': 'work item assignee',
                'verbose_name_plural': 'work item assignees',
                'db_table': 'work_items_assignee',
                'constraints': [models.UniqueConstraint(fields=('work_item', 'user'), name='work_items_workitemassignee_unique_work_item_user')],
            },
        ),
    ]
