# Generated by Django 5.2.17 on 2026-08-14 16:02

import django.db.models.deletion
from django.db import migrations, models


def populate_work_item_definitions(apps, schema_editor):
    """Create default Type/Status definitions for each Project and map existing WorkItems."""
    WorkItemTypeDefinition = apps.get_model("projects", "WorkItemTypeDefinition")
    WorkItemStatusDefinition = apps.get_model("projects", "WorkItemStatusDefinition")
    Project = apps.get_model("projects", "Project")
    WorkItem = apps.get_model("work_items", "WorkItem")

    type_map = {
        "epic": "Epic",
        "milestone": "Milestone",
        "deliverable": "Deliverable",
        "task": "Task",
    }

    status_map = {
        "todo": ("Todo", "todo", True),
        "in_progress": ("In Progress", "in_progress", False),
        "review": ("Review", "review", False),
        "done": ("Done", "done", False),
    }

    for project in Project.objects.all():
        # Create TypeDefinitions
        type_defs = {}
        for old_val, display_name in type_map.items():
            defn, _ = WorkItemTypeDefinition.objects.get_or_create(
                project=project,
                name__iexact=display_name,
                defaults={
                    "name": display_name,
                    "order": list(type_map.keys()).index(old_val),
                    "active": True,
                },
            )
            type_defs[old_val] = defn

        # Create StatusDefinitions
        status_defs = {}
        for old_val, (display_name, category, is_default) in status_map.items():
            defn, _ = WorkItemStatusDefinition.objects.get_or_create(
                project=project,
                name__iexact=display_name,
                defaults={
                    "name": display_name,
                    "category": category,
                    "order": list(status_map.keys()).index(old_val),
                    "active": True,
                    "is_default": is_default,
                },
            )
            status_defs[old_val] = defn

        # Map existing WorkItems to their Project's definitions
        work_items = WorkItem.objects.filter(project=project)
        updates = []
        for wi in work_items:
            if wi.type in type_defs:
                wi.type_definition = type_defs[wi.type]
            if wi.status in status_defs:
                wi.status_definition = status_defs[wi.status]
            updates.append(wi)

        if updates:
            WorkItem.objects.bulk_update(
                updates, ["type_definition", "status_definition"],
                batch_size=500,
            )


def reverse_populate(apps, schema_editor):
    """Clear definition references on reversal."""
    WorkItem = apps.get_model("work_items", "WorkItem")
    WorkItem.objects.update(type_definition=None, status_definition=None)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_workitemlabeldefinition_workitemstatusdefinition_and_more'),
        ('work_items', '0002_workitemcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='status_definition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='work_items', to='projects.workitemstatusdefinition'),
        ),
        migrations.AddField(
            model_name='workitem',
            name='type_definition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='work_items', to='projects.workitemtypedefinition'),
        ),
        migrations.CreateModel(
            name='WorkItemLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_item_relations', to='projects.workitemlabeldefinition')),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_relations', to='work_items.workitem')),
            ],
            options={
                'verbose_name': 'work item label',
                'verbose_name_plural': 'work item labels',
                'db_table': 'work_items_workitem_label',
                'constraints': [models.UniqueConstraint(fields=('work_item', 'label'), name='work_items_workitemlabel_unique_work_item_label')],
            },
        ),
        migrations.RunPython(
            populate_work_item_definitions,
            reverse_populate,
        ),
    ]
