# Generated by Django 5.2.17 on 2026-09-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_items', '0004_complete_workitem_definition_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='board_position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
