# Generated by Django 5.2.17 on 2026-09-03 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_items', '0005_workitem_board_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='work_items.workitem'),
        ),
    ]
