# Generated by Django 5.2.17 on 2026-09-17 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_workitemtypedefinition_kind'),
        ('research_groups', '0001_initial'),
        ('work_items', '0006_alter_workitem_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyWorkPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_mode', models.CharField(choices=[('board', 'Board'), ('list', 'List')], default='board', max_length=8)),
                ('work_item_types', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('projects', models.ManyToManyField(blank=True, db_table='work_items_myworkpreferences_projects', related_name='my_work_preferences', to='projects.project')),
                ('research_groups', models.ManyToManyField(blank=True, db_table='work_items_myworkpreferences_research_groups', related_name='my_work_preferences', to='research_groups.researchgroup')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_work_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'my work preferences',
                'verbose_name_plural': 'my work preferences',
                'db_table': 'work_items_my_work_preferences',
            },
        ),
    ]
