# Generated by Django 5.2.17 on 2026-09-28 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_items', '0007_myworkpreferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyWorkBoardPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_category', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('review', 'Review'), ('done', 'Done')], max_length=16)),
                ('position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_work_board_positions', to=settings.AUTH_USER_MODEL)),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_work_board_positions', to='work_items.workitem')),
            ],
            options={
                'verbose_name': 'my work board position',
                'verbose_name_plural': 'my work board positions',
                'db_table': 'work_items_my_work_board_position',
                'constraints': [models.UniqueConstraint(fields=('user', 'work_item'), name='work_items_myworkboardposition_unique_user_work_item')],
            },
        ),
    ]
