# Generated by Django 5.2.17 on 2026-08-14 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_archived_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItemLabelDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_definitions', to='projects.project')),
            ],
            options={
                'verbose_name': 'work item label definition',
                'verbose_name_plural': 'work item label definitions',
                'db_table': 'projects_workitem_label_definition',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RunSQL(
            sql=(
                "CREATE UNIQUE INDEX projects_workitem_label_def_project_name_lower_uniq "
                "ON projects_workitem_label_definition (project_id, lower(name))"
            ),
            reverse_sql=(
                "DROP INDEX projects_workitem_label_def_project_name_lower_uniq"
            ),
        ),
        migrations.CreateModel(
            name='WorkItemStatusDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('review', 'Review'), ('done', 'Done')], default='todo', max_length=16)),
                ('order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_definitions', to='projects.project')),
            ],
            options={
                'verbose_name': 'work item status definition',
                'verbose_name_plural': 'work item status definitions',
                'db_table': 'projects_workitem_status_definition',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RunSQL(
            sql=(
                "CREATE UNIQUE INDEX projects_workitem_status_def_project_name_lower_uniq "
                "ON projects_workitem_status_definition (project_id, lower(name))"
            ),
            reverse_sql=(
                "DROP INDEX projects_workitem_status_def_project_name_lower_uniq"
            ),
        ),
        migrations.CreateModel(
            name='WorkItemTypeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_definitions', to='projects.project')),
            ],
            options={
                'verbose_name': 'work item type definition',
                'verbose_name_plural': 'work item type definitions',
                'db_table': 'projects_workitem_type_definition',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RunSQL(
            sql=(
                "CREATE UNIQUE INDEX projects_workitem_type_def_project_name_lower_uniq "
                "ON projects_workitem_type_definition (project_id, lower(name))"
            ),
            reverse_sql=(
                "DROP INDEX projects_workitem_type_def_project_name_lower_uniq"
            ),
        ),
    ]
