# Generated by Django 5.2.17 on 2026-10-03 10:28

import django.db.models.deletion
from django.db import migrations, models


"""Personal Project navigation recency (Project Quick Access, V1).

Creates ``ProjectNavigationRecency`` — one row per current
``ProjectMembership`` (OneToOne, ON DELETE CASCADE) persisting the
user's personal ``last_opened_at`` (server-owned) for the Project the
membership grants access to.

Relational invariants (no second uniqueness system needed):
- the OneToOne to ``projects_membership`` guarantees at most one
  recency row per membership, and the membership's existing
  UNIQUE(project, user) therefore also bounds recency to one row per
  (user, project);
- ON DELETE CASCADE deletes the recency row with its membership
  (offboarding / membership removal), so a later-recreated
  membership starts with no historical recency;
- because the membership's composite FKs already pin it to the
  Project's Research Group and the user's current
  ResearchGroupMembership, the recency row can never outlive its
  access relationship or survive as an independent
  authorization-bearing relation.

Non-destructive: pure table creation, no data changes.
"""


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_workitemtypedefinition_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectNavigationRecency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_opened_at', models.DateTimeField()),
                ('project_membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='navigation_recency', to='projects.projectmembership')),
            ],
            options={
                'verbose_name': 'project navigation recency',
                'verbose_name_plural': 'project navigation recencies',
                'db_table': 'projects_navigation_recency',
            },
        ),
    ]
