# Generated by Django 5.2.17 on 2026-09-29 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('pinned', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='personal_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'personal note',
                'verbose_name_plural': 'personal notes',
                'db_table': 'personal_notes_personal_note',
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['user_id', 'archived_at', '-updated_at', '-id'], name='pn_user_archive_idx')],
            },
        ),
    ]
